from __future__ import annotations
from abc import ABC, abstractmethod
from domain.slips.slip import BetSlip

class SportsbookAdapter(ABC):
    @property
    @abstractmethod
    def name(self) -> str: ...

    def map_market(self, canonical_market: str) -> str:
        from sportsbooks.mappings import to_sportsbook_market
        return to_sportsbook_market(canonical_market, self.name)

    def format_slip(self, slip: BetSlip) -> dict:
        """Return sportsbook-specific formatting — never invents booking codes."""
        selections = []
        for s in slip.selections:
            selections.append({
                "event": s.event_label,
                "event_id": s.event_id,
                "market": self.map_market(s.market),
                "canonical_market": s.market,
                "selection": s.selection,
                "odds": s.odds,
                "edge": s.edge,
                "confidence": s.confidence,
            })
        out = {
            "sportsbook": self.name,
            "selections": selections,
            "total_odds": slip.compute_total_odds(),
            "count": len(selections),
        }
        # Booking codes are external reference only — never invented
        if slip.booking_code:
            out["booking_code"] = slip.booking_code
            out["booking_code_note"] = "external reference, not generated by Apex Sports"
        return out

    def parse_booking_code(self, code: str) -> str:
        """Store external reference only if supplied by user/integration."""
        code = code.strip()
        if not code or len(code) < 3:
            raise ValueError("invalid booking code — must be supplied by sportsbook")
        return code
